# By default, SwiftLint uses a set of sensible default rules you can adjust:

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - vendor
  - Derived

line_length:
    warning: 200
    ignores_comments: true

identifier_name:
  min_length: 2 # only min_length

disabled_rules: # rule identifiers to exclude from running
  - unused_capture_list
  - trailing_comma
  - multiple_closures_with_trailing_closure

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - implicit_return
